name: Run Java Test with Maven
on: workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      run: mvn -f second.action/pom.xml clean test
    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-output-artifacts
        path: second.action/target/surefire-reports/*.*
  
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Download Test Report
      uses: actions/download-artifact@v3
      with:
        name: test-output-artifacts
    - name: Verify Download
      run: ls
    - name: Deploy
      run: echo "Deploying"
  